---
stages:
  - verify

build:
  stage: verify
  image: golang:1.24.5-alpine
  script:
    - apk add --no-cache git make
    - make build
  artifacts:
    paths:
      - img-upgr
    expire_in: 1 hour
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

golangci-lint:
  stage: verify
  image: golangci/golangci-lint:v2.3.0-alpine
  script:
    - apk add --no-cache git make
    - make lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

go-mod-tidy:
  stage: verify
  image: golang:1.24.5-alpine
  script:
    - apk add --no-cache git make
    - make check-mod
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

go-fmt:
  stage: verify
  image: golang:1.24.5-alpine
  script:
    - apk add --no-cache git make
    - make check-fmt
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"