---
stages:
  - build
  - static-analysis
  - unit-tests

build:
  stage: build
  image: golang:1.24.5-alpine
  script:
    - apk add --no-cache git make
    - make build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

golangci-lint:
  stage: static-analysis
  image: golangci/golangci-lint:v2.3.0-alpine
  script:
    - apk add --no-cache git make
    - make lint
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

go-mod-tidy:
  stage: static-analysis
  image: golang:1.24.5-alpine
  script:
    - apk add --no-cache git make
    - make check-mod
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

go-fmt:
  stage: static-analysis
  image: golang:1.24.5-alpine
  script:
    - apk add --no-cache git make
    - make check-fmt
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

go-test:
  stage: unit-tests
  image: golang:1.24.5-alpine
  script:
    - apk add --no-cache git make
    - make test
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"

go-test-race:
  stage: unit-tests
  image: golang:1.24.5-alpine
  script:
    - apk add --no-cache git make gcc musl-dev
    - make test-race
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "master"